  /* DO NOT EDIT THIS FILE - it is machine generated */
  #include <jni.h>
  /* Header for class com_android_jnimodule_jni_JNIEntity */

  #ifndef _Included_com_android_jnimodule_jni_JNIEntity
  #define _Included_com_android_jnimodule_jni_JNIEntity
  #ifdef __cplusplus
  extern "C" {
  #endif
  /*
   * Class:     com_android_jnimodule_jni_JNIEntity
   * Method:    helljni
   * Signature: (Ljava/lang/String;)Ljava/lang/String;
   */
  JNIEXPORT jstring JNICALL Java_com_android_jnimodule_jni_JNIEntity_helljni
    (JNIEnv *, jclass, jstring);

  #ifdef __cplusplus
  }
  #endif
  #endif
